#!/usr/bin/env python3
"""
cli/aios.py  —  AIOS Command-Line Interface  (v0.3.0)
───────────────────────────────────────────────────────
Complete CLI including all original commands PLUS Phase 2
system service commands: start, stop, restart, status, logs.

Install path: /opt/aios/cli/aios.py
Global wrapper: /usr/local/bin/aios  (generated by install.sh)
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import typer
from rich import box, print as rprint
from rich.console import Console
from rich.panel import Panel
from rich.progress import (BarColumn, Progress, SpinnerColumn,
                           TextColumn, TimeElapsedColumn)
from rich.table import Table

# ── Bootstrap sys.path ────────────────────────────────────────────────────────
sys.path.insert(0, str(Path(__file__).parent))
from aios_cli._utils import run, py_cmd, TEMPLATES

# ── Service commands (Phase 2) ────────────────────────────────────────────────
from aios_cli.commands.service import (
    cmd_start, cmd_stop, cmd_restart, cmd_status, cmd_logs,
    AIOS_PORT,
)

# ── App & console ─────────────────────────────────────────────────────────────
app    = typer.Typer(name="aios", help="AIOS — AI Developer OS CLI", no_args_is_help=True)
docker = typer.Typer(help="Manage AIOS Docker containers")
app.add_typer(docker, name="docker")

console = Console()

AIOS_PROJECTS_DIR = Path.home() / "aios-projects"
AIOS_VERSION      = "0.3.0"

LOGO = """\
[bold cyan]
   █████╗ ██╗ ██████╗ ███████╗
  ██╔══██╗██║██╔═══██╗██╔════╝
  ███████║██║██║   ██║███████╗
  ██╔══██║██║██║   ██║╚════██║
  ██║  ██║██║╚██████╔╝███████║
  ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚══════╝
[/bold cyan][dim]  AI Developer OS  v""" + AIOS_VERSION + """[/dim]
"""

# ═══════════════════════════════════════════════════════════════════════════════
# PHASE 2 — Service lifecycle commands
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def start(
    no_browser: bool = typer.Option(False, "--no-browser", help="Don't open browser"),
    port: int        = typer.Option(AIOS_PORT, "--port", "-p", help="Backend port"),
) -> None:
    """Start the AIOS backend and open the dashboard."""
    cmd_start(no_browser=no_browser, port=port)


@app.command()
def stop() -> None:
    """Stop the AIOS backend."""
    cmd_stop()


@app.command()
def restart() -> None:
    """Restart the AIOS backend."""
    cmd_restart()


@app.command()
def status() -> None:
    """Show AIOS system status (backend, docker, GPU)."""
    cmd_status()


@app.command()
def logs(
    lines:  int  = typer.Option(50,   "--lines", "-n"),
    follow: bool = typer.Option(True, "--follow/--no-follow", "-f"),
) -> None:
    """Stream or tail AIOS backend logs."""
    cmd_logs(lines=lines, follow=follow)


# ═══════════════════════════════════════════════════════════════════════════════
# aios version
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def version() -> None:
    """Print AIOS version."""
    console.print(f"[bold cyan]AIOS[/bold cyan] v{AIOS_VERSION}")


# ═══════════════════════════════════════════════════════════════════════════════
# aios new
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def new(
    name: str = typer.Argument(..., help="Project name (creates ~/aios-projects/<name>)"),
    template: str = typer.Option(
        "blank", "--template", "-t",
        help=f"Project template: {', '.join(TEMPLATES)}",
    ),
    no_venv:    bool = typer.Option(False, "--no-venv",    help="Skip venv creation"),
    no_install: bool = typer.Option(False, "--no-install", help="Skip pip install"),
) -> None:
    """
    Create a new AI project from a template.

    \b
    Examples:
      aios new my-model
      aios new bert-finetune --template nlp
      aios new rag-app --template llm --no-venv
    """
    if template not in TEMPLATES:
        console.print(f"[red]Unknown template '{template}'. Available: {', '.join(TEMPLATES)}[/red]")
        raise typer.Exit(1)

    project_dir = AIOS_PROJECTS_DIR / name
    if project_dir.exists():
        console.print(f"[red]Project '{name}' already exists at {project_dir}[/red]")
        raise typer.Exit(1)

    tmpl = TEMPLATES[template]
    console.print(LOGO)
    console.print(f"[bold cyan]Creating project:[/bold cyan] {name}")
    console.print(f"[dim]Template:[/dim] {template} — {tmpl['description']}")
    console.print(f"[dim]Location:[/dim] {project_dir}\n")

    AIOS_PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    project_dir.mkdir(parents=True)
    for d in tmpl["dirs"]:
        (project_dir / d).mkdir(parents=True, exist_ok=True)
        (project_dir / d / ".gitkeep").touch()

    (project_dir / ".aios-env").write_text(
        f"template={template}\n"
        f"created={datetime.now().isoformat()}\n"
        f"name={name}\n"
        f"aios_version={AIOS_VERSION}\n"
    )

    nb_stub = json.dumps({
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
        "cells": [
            {"cell_type": "markdown", "metadata": {}, "source": [f"# {name}\n\nGenerated by AIOS  \nTemplate: `{template}`"]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": ["# Your code here\n"]},
        ],
    }, indent=2)
    for nb in tmpl["notebooks"]:
        (project_dir / nb).write_text(nb_stub)

    (project_dir / "README.md").write_text(
        f"# {name}\n\n> Template: `{template}` — {tmpl['description']}\n\n"
        f"## Setup\n\n```bash\ncd ~/aios-projects/{name}\nsource .venv/bin/activate\njupyter lab\n```\n"
    )
    (project_dir / "requirements.txt").write_text("\n".join(tmpl["packages"]) + "\n")
    console.print("[green]✓[/green] Project structure created")

    if not no_venv:
        console.print("[dim]  Creating virtual environment...[/dim]", end="")
        code, _, err = run([py_cmd(), "-m", "venv", str(project_dir / ".venv")])
        if code == 0:
            console.print("\r[green]✓[/green] Virtual environment created (.venv)")
        else:
            console.print(f"\r[yellow]⚠[/yellow] venv failed: {err}")
            no_install = True

    if not no_install and tmpl["packages"]:
        venv_pip = project_dir / ".venv" / "bin" / "pip"
        pip_exec = str(venv_pip) if venv_pip.exists() else py_cmd()
        pip_args = [pip_exec, "install"] if pip_exec.endswith("pip") else [pip_exec, "-m", "pip", "install"]
        console.print(f"[dim]  Installing {len(tmpl['packages'])} package(s)...[/dim]")
        with Progress(SpinnerColumn(), TextColumn("{task.description}"), TimeElapsedColumn(), console=console) as p:
            task = p.add_task("pip install...", total=None)
            code, _, _ = run(pip_args + tmpl["packages"], timeout=300)
            p.stop()
        console.print("[green]✓[/green] Packages installed" if code == 0 else "[yellow]⚠[/yellow] pip had errors (install manually)")

    console.print()
    console.print(Panel(
        f"[bold white]{name}[/bold white] is ready!\n\n"
        f"[dim]Location:[/dim]  {project_dir}\n"
        f"[dim]Template:[/dim]  {template}\n\n"
        f"[bold cyan]Next steps:[/bold cyan]\n"
        f"  cd ~/aios-projects/{name}\n"
        f"  source .venv/bin/activate\n"
        f"  aios notebook",
        title="[bold green]✓ Project Created[/bold green]",
        border_style="green",
    ))


# ═══════════════════════════════════════════════════════════════════════════════
# aios notebook
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def notebook(
    port: int = typer.Option(8888, "--port", "-p"),
    no_browser: bool = typer.Option(False, "--no-browser"),
    directory: Optional[str] = typer.Option(None, "--dir", "-d"),
) -> None:
    """Launch JupyterLab."""
    if not shutil.which("jupyter"):
        console.print("[red]Jupyter not found.[/red]  Install: [bold]pip install jupyterlab[/bold]")
        raise typer.Exit(1)
    root = directory or str(AIOS_PROJECTS_DIR)
    Path(root).mkdir(parents=True, exist_ok=True)
    cmd = ["jupyter", "lab", f"--port={port}", f"--notebook-dir={root}"]
    if no_browser:
        cmd.append("--no-browser")
    console.print(f"[bold cyan]Starting JupyterLab[/bold cyan]  →  http://localhost:{port}")
    os.execvp("jupyter", cmd)


# ═══════════════════════════════════════════════════════════════════════════════
# aios docker
# ═══════════════════════════════════════════════════════════════════════════════

DOCKER_IMAGES = {
    "nlp":  "aiosproject/aios-nlp:latest",
    "cv":   "aiosproject/aios-cv:latest",
    "llm":  "aiosproject/aios-llm:latest",
    "base": "aiosproject/aios-base:latest",
}


@docker.command("run")
def docker_run(
    env_type: str = typer.Argument(..., help=f"Container type: {', '.join(DOCKER_IMAGES)}"),
    port: int     = typer.Option(8888, "--port", "-p"),
    gpu: bool     = typer.Option(True, "--gpu/--no-gpu"),
) -> None:
    """Start an AIOS Docker AI environment."""
    if env_type not in DOCKER_IMAGES:
        console.print(f"[red]Unknown type '{env_type}'. Choose: {', '.join(DOCKER_IMAGES)}[/red]")
        raise typer.Exit(1)
    if not shutil.which("docker"):
        console.print("[red]Docker not found.[/red]  Run [bold]./install.sh[/bold] first.")
        raise typer.Exit(1)
    image = DOCKER_IMAGES[env_type]
    name  = f"aios-{env_type}"
    run(["docker", "rm", "-f", name])
    cmd = ["docker", "run", "--detach", "--name", name,
           "--publish", f"{port}:8888",
           "--volume", f"{AIOS_PROJECTS_DIR}:/workspace"]
    if gpu:
        cmd += ["--gpus", "all"]
    cmd.append(image)
    console.print(f"[bold cyan]Starting:[/bold cyan] {name}  →  http://localhost:{port}")
    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console) as p:
        task = p.add_task(f"Pulling {image}...", total=None)
        code, out, err = run(cmd, timeout=120)
        p.stop()
    if code == 0:
        console.print(f"[green]✓[/green] {name} started  [dim](ID: {out[:12]})[/dim]")
    else:
        console.print(f"[red]✗ Failed:[/red] {err}")
        raise typer.Exit(1)


@docker.command("stop")
def docker_stop(name: str = typer.Argument(...)) -> None:
    """Stop a running AIOS container."""
    code, _, err = run(["docker", "stop", name], timeout=15)
    console.print(f"[green]✓[/green] Stopped {name}" if code == 0 else f"[red]✗[/red] {err}")


@docker.command("list")
def docker_list() -> None:
    """List running AIOS containers."""
    code, out, _ = run(["docker", "ps", "--format", "{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"])
    t = Table(box=box.ROUNDED, border_style="dim", header_style="bold cyan")
    t.add_column("Name"); t.add_column("Image"); t.add_column("Status"); t.add_column("Ports")
    if code == 0 and out:
        for line in out.splitlines():
            parts = line.split("\t")
            t.add_row(*parts[:4]) if len(parts) >= 4 else None
    else:
        t.add_row("[dim]No containers running[/dim]", "", "", "")
    console.print(t)


# ═══════════════════════════════════════════════════════════════════════════════
# aios gpu
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def gpu(
    watch:   bool = typer.Option(False, "--watch", "-w"),
    as_json: bool = typer.Option(False, "--json"),
) -> None:
    """Show GPU utilisation, VRAM, temperature, and power."""

    def _collect() -> dict:
        if not shutil.which("nvidia-smi"):
            return {"vendor": None, "gpus": []}
        code, out, _ = run([
            "nvidia-smi",
            "--query-gpu=index,name,driver_version,utilization.gpu,utilization.memory,"
            "memory.used,memory.total,temperature.gpu,power.draw,power.limit",
            "--format=csv,noheader,nounits",
        ])
        if code != 0:
            return {"vendor": "NVIDIA", "gpus": []}
        gpus = []
        for line in out.splitlines():
            p = [x.strip() for x in line.split(",")]
            if len(p) < 10:
                continue
            gpus.append({
                "index": int(p[0]), "name": p[1], "driver": p[2],
                "gpu_util":    float(p[3]) if p[3].replace(".", "").isdigit() else 0,
                "mem_used":    int(p[5])   if p[5].isdigit() else 0,
                "mem_total":   int(p[6])   if p[6].isdigit() else 0,
                "temp":        int(p[7])   if p[7].isdigit() else 0,
                "power_draw":  float(p[8]) if p[8].replace(".", "").isdigit() else 0,
                "power_limit": float(p[9]) if p[9].replace(".", "").isdigit() else 0,
            })
        return {"vendor": "NVIDIA", "gpus": gpus}

    def _bar(pct: int, w: int = 20) -> str:
        f = round(pct / 100 * w)
        return "█" * f + "░" * (w - f)

    def _render(data: dict) -> None:
        if not data["gpus"]:
            console.print(Panel("[yellow]No GPU detected — CPU-only mode[/yellow]",
                                title="AIOS GPU", border_style="yellow"))
            return
        for g in data["gpus"]:
            mem_pct = round(g["mem_used"] / max(g["mem_total"], 1) * 100)
            tc = "red" if g["temp"] > 80 else "yellow" if g["temp"] > 70 else "green"
            body = (
                f"[bold white]GPU {g['index']}:[/bold white] [cyan]{g['name']}[/cyan]  "
                f"[dim]Driver {g['driver']}[/dim]\n\n"
                f"  [dim]GPU   [/dim] [{_bar(int(g['gpu_util']))}] [bold yellow]{g['gpu_util']:.0f}%[/bold yellow]\n"
                f"  [dim]VRAM  [/dim] [{_bar(mem_pct)}] [bold yellow]{g['mem_used']:,}/{g['mem_total']:,} MB[/bold yellow]"
                f"  [dim]({mem_pct}%)[/dim]\n"
                f"  [dim]Temp  [/dim] [{_bar(g['temp'], 10)}] [{tc}]{g['temp']}°C[/{tc}]\n"
                f"  [dim]Power [/dim] [{_bar(round(g['power_draw']/max(g['power_limit'],1)*100))}] "
                f"[bold]{g['power_draw']:.0f}W / {g['power_limit']:.0f}W[/bold]\n"
            )
            console.print(Panel(body, title="[bold magenta]AIOS GPU[/bold magenta]",
                                border_style="magenta", padding=(0, 2)))

    if watch:
        try:
            while True:
                console.clear()
                data = _collect()
                print(json.dumps(data, indent=2)) if as_json else _render(data)
                console.print("[dim]  Ctrl+C to stop[/dim]")
                time.sleep(2)
        except KeyboardInterrupt:
            console.print("\n[dim]Stopped.[/dim]")
    else:
        data = _collect()
        print(json.dumps(data, indent=2)) if as_json else _render(data)


# ═══════════════════════════════════════════════════════════════════════════════
# aios doctor / verify
# ═══════════════════════════════════════════════════════════════════════════════

@app.command()
def doctor(
    category: Optional[str] = typer.Option(None, "--category", "-c",
        help="core | ml | gpu | docker | jupyter | system"),
    as_json: bool = typer.Option(False, "--json"),
    quiet:   bool = typer.Option(False, "--quiet", "-q"),
) -> None:
    """Run a full environment health check."""

    def _chk_python():
        v = sys.version_info
        ok = v >= (3, 10)
        return ok, f"Python {v.major}.{v.minor}.{v.micro}" + ("" if ok else " (3.10+ required)")

    def _chk_cmd(cmd):
        if not shutil.which(cmd):
            return False, f"'{cmd}' not found"
        code, out, err = run([cmd, "--version"])
        txt = (out or err).splitlines()[0][:60] if (out or err) else "ok"
        return code == 0, txt

    def _chk_pkg(pkg, imp=None):
        imp = imp or pkg.replace("-", "_")
        code, out, err = run([py_cmd(), "-c",
            f"import {imp}; v=getattr({imp},'__version__','ok'); print(v)"], timeout=15)
        return code == 0, (out or err.strip()[:60])

    def _chk_docker():
        if not shutil.which("docker"):
            return False, "Not installed"
        code, out, _ = run(["docker", "info", "--format", "{{.ServerVersion}}"])
        return code == 0, f"Docker {out}" if code == 0 else "Daemon not running"

    def _chk_nvidia():
        if not shutil.which("nvidia-smi"):
            return False, "nvidia-smi not found"
        code, out, _ = run(["nvidia-smi", "--query-gpu=name,driver_version", "--format=csv,noheader"])
        return code == 0, out.splitlines()[0][:60] if code == 0 else "nvidia-smi failed"

    def _chk_cuda():
        code, out, _ = run([py_cmd(), "-c",
            "import torch; c=torch.cuda.is_available(); d=torch.cuda.device_count(); "
            "print(f'CUDA={c} devices={d}')"], timeout=30)
        if code != 0:
            return False, "PyTorch not installed"
        return out.startswith("CUDA=True"), out.strip()

    def _chk_disk():
        t, u, f = shutil.disk_usage("/")
        gb = f // (2**30)
        return gb >= 5, f"{gb} GB free" + ("" if gb >= 5 else " (5 GB+ recommended)")

    CHECKS = [
        ("Python 3.10+",   "core",    _chk_python,                          True),
        ("pip",            "core",    lambda: _chk_cmd("pip"),               True),
        ("git",            "core",    lambda: _chk_cmd("git"),               True),
        ("Docker",         "docker",  _chk_docker,                           False),
        ("PyTorch",        "ml",      lambda: _chk_pkg("torch"),             False),
        ("Transformers",   "ml",      lambda: _chk_pkg("transformers"),      False),
        ("NumPy",          "ml",      lambda: _chk_pkg("numpy"),             False),
        ("pandas",         "ml",      lambda: _chk_pkg("pandas"),            False),
        ("NVIDIA GPU",     "gpu",     _chk_nvidia,                           False),
        ("PyTorch + CUDA", "gpu",     _chk_cuda,                             False),
        ("JupyterLab",     "jupyter", lambda: _chk_cmd("jupyter"),           False),
        ("Disk Space",     "system",  _chk_disk,                             False),
    ]

    checks = [(n, c, fn, crit) for n, c, fn, crit in CHECKS
              if category is None or c == category.lower()]

    results: dict = {}
    passed = failed = 0

    with Progress(SpinnerColumn(), TextColumn("{task.description}"), console=console, transient=True) as p:
        task = p.add_task("Checking...", total=len(checks))
        for name, cat, fn, critical in checks:
            p.update(task, description=f"Checking {name}...")
            ok_flag, msg = fn()
            results[name] = {"category": cat, "ok": ok_flag, "msg": msg, "critical": critical}
            passed += ok_flag
            failed += not ok_flag
            p.advance(task)

    if as_json:
        print(json.dumps({"passed": passed, "failed": failed, "results": results}, indent=2))
        return

    cats = list(dict.fromkeys(c for _, c, _, _ in checks))
    for cat in cats:
        cat_results = {n: r for n, r in results.items() if r["category"] == cat}
        if quiet and all(r["ok"] for r in cat_results.values()):
            continue
        t = Table(box=box.ROUNDED, border_style="dim", header_style="bold cyan", min_width=64)
        t.add_column("Component", style="bold white", min_width=20)
        t.add_column("Status", justify="center", min_width=8)
        t.add_column("Detail", style="dim", min_width=36)
        for name, r in cat_results.items():
            if quiet and r["ok"]:
                continue
            icon = "[green]  ✓  [/green]" if r["ok"] else "[red]  ✗  [/red]"
            t.add_row(name, icon, r["msg"])
        console.print(f"\n[bold cyan]{cat.upper()}[/bold cyan]")
        console.print(t)

    console.print()
    console.print(Panel(
        f"[green]Passed: {passed}[/green]   [red]Failed: {failed}[/red]\n\n" + (
            "[green]🎉 Environment looks great![/green]"
            if failed == 0 else
            f"[yellow]⚠  {failed} check(s) need attention.[/yellow]\n"
            "[dim]Run [bold]aios wizard[/bold] for automated fixes.[/dim]"
        ),
        title="[bold magenta]AIOS Doctor[/bold magenta]",
        border_style="green" if failed == 0 else "yellow",
    ))
    raise typer.Exit(0 if failed == 0 else 1)


@app.command(hidden=True)
def verify(
    category: Optional[str] = typer.Option(None, "--category", "-c"),
    as_json:  bool = typer.Option(False, "--json"),
    quiet:    bool = typer.Option(False, "--quiet", "-q"),
) -> None:
    """Alias for `aios doctor`."""
    doctor(category=category, as_json=as_json, quiet=quiet)


# ═══════════════════════════════════════════════════════════════════════════════
# Entry point
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    app()
